name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Run sync script and commit changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: |
          # Run the sync script
          python sync_leetcode.py
          
          echo "Checking Git status before staging..."
          git status
          
          # Stage any changes
          git add -A
          
          echo "Checking staged changes..."
          git diff --staged --name-status
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            # Show what will be committed
            git status --short
            
            # Commit and push
            git commit -m "sync: Update LeetCode solutions [skip ci]"
            
            echo "Pushing changes..."
            git pull --rebase origin main
            git push origin main
            
            echo "Commit successful. Final status:"
            git log -1 --name-status
          fi