name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 0 1 * *'    # Run at midnight (00:00) on the 1st day of every month
  workflow_dispatch:        # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Get full history
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check for cache file
        id: check-cache
        run: |
          if [ -f "solutions_cache.json" ]; then
            echo "Cache file exists"
            echo "cache_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Cache file does not exist, will be created"
            echo "cache_exists=false" >> $GITHUB_OUTPUT
            echo "{}" > solutions_cache.json
          fi
          
      - name: Run sync script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: python sync_leetcode.py

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if needed
        if: steps.git-check.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add solutions_cache.json
          git add .
          
          # Different commit messages based on cache existence
          if [ "${{ steps.check-cache.outputs.cache_exists }}" == "true" ]; then
            git commit -m "sync: Update LeetCode solutions and cache [skip ci]"
          else
            git commit -m "sync: Initial cache creation and solutions sync [skip ci]"
          fi
          
          git pull --rebase origin main
          git push origin main