name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 0 1 * *'    # Run at midnight (00:00) on the 1st day of every month
  workflow_dispatch:        # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Get full history
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin main
          git reset --hard origin/main
      
      - name: Run sync script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: python sync_leetcode.py

      - name: Commit and push changes
        run: |
          # Check if there are any changes
          if git status --porcelain | grep .; then
            echo "Changes detected"
            
            # Stage all changes
            git add -A
            
            # Commit with appropriate message
            git commit -m "sync: Update LeetCode solutions and cache [skip ci]"
            
            # Pull latest changes and rebase
            git pull --rebase origin main
            
            # Push changes
            git push origin main
          else
            echo "No changes to commit"
          fi