name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 0 1 * *'    # Run at midnight on the 1st day of every month
  workflow_dispatch:        # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Ensure the repository is in safe directory list
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run sync script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: python sync_leetcode.py
        
      - name: Check and commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected"
            git add .
            git commit -m "Sync LeetCode solutions [skip ci]"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Debug information
        if: always()
        run: |
          echo "Repository status:"
          git status
          echo "Latest commit:"
          git log -1
          echo "Remote configuration:"
          git remote -v